# Generated by Django 5.1.7 on 2025-03-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=555)),
                ("description", models.TextField()),
                ("video", models.FileField(blank=True, null=True, upload_to="videos/")),
                ("image", models.FileField(blank=True, null=True, upload_to="images/")),
                ("craeted_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
